name: MacOS Build & Release

# Must match the linux release (future migration to use composite actions)
# be careful due to gh action minute cost

on:
    release:
        types: [created]
#   push:
#     branches: [main]
#   pull_request:


permissions:
  contents: write

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-n-stash:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --break-system-packages

      - name: Build package
        run: make install

      #! MacOS specific
      - run: mv /usr/local/bin/docci /usr/local/bin/docci_macos

      - name: Upload docci artifact
        uses: actions/upload-artifact@v4.6.1
        if: github.event_name == 'pull_request'
        with:
          name: docci
          retention-days: 1
          path: /usr/local/bin/docci_macos

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            /usr/local/bin/docci_macos

  test-e2e:
    runs-on: macos-latest
    needs: build-n-stash
    if: github.event_name != 'release'
    steps:
      - uses: actions/checkout@v4

      - run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Download docci binary
        uses: actions/download-artifact@v4.1.9
        with:
          name: docci
          path: /usr/local/bin
      - run: chmod a+rx /usr/local/bin/docci_macos

      # python runner in another job
      - name: Run integrations as binary
        run: EXEC_BINARY=/usr/local/bin/docci_macos make test-examples

