name: Release

on:
  pull_request: {}
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --break-system-packages

      # - run: sudo mkdir -p /usr/local/bin

      - name: Build package
        run: make install

      - name: Upload docs-ci artifact
        uses: actions/upload-artifact@v4.6.1
        if: github.event_name == 'pull_request'
        with:
          name: docs-ci
          path: /usr/local/bin/docs-ci

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            /usr/local/bin/docs-ci
  test-e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check if PR
        if: github.event_name != 'pull_request' && github.event_name != 'push'
        run: |
          echo "This job is only for pull_request & push"
          exit 0

      # - run: sudo mkdir -p /usr/local/bin
      - run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Download docs-ci Bin
        uses: actions/download-artifact@v4.1.9
        with:
          name: docs-ci
          path: /usr/local/bin

      - name: Run 1-node
        run: docs-ci ./examples/1-node/config.json

