name: Release

on:
  pull_request: {}
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # staticx issue requires this -- https://github.com/JonathonReinhart/staticx/issues/188
      - name: Setup Python
        run: sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt-get update && sudo apt-get install python3.12

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller staticx --break-system-packages

      - name: Build package
        env:
          IS_ACTION: true # else we move to /usr/bin/local/
        run: make install

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/docs-ci

