name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt --break-system-packages

      - name: Run Python unit tests
        run: make tests

      - name: Run integration tests (python)
        run: make run-integrations
